return {
  water = {
    label = "Water",
    icon = "water",
    domain = "consumable",
    stackable = true,
    maxStack = 10,
    buy = 6,
    sell = 1,
    tags = { "legal", "consumable", "src.shop.convenience", "src.shop.food" },
    effects = { thirst = -18 },
  },

  spring_water = {
    label = "Spring Water",
    icon = "spring-water",
    domain = "consumable",
    stackable = true,
    maxStack = 10,
    buy = 10,
    sell = 2,
    tags = { "legal", "consumable", "src.shop.convenience" },
    effects = { thirst = -26 },
  },

  soda = {
    label = "Soda",
    icon = "coke-can",
    domain = "consumable",
    stackable = true,
    maxStack = 10,
    buy = 8,
    sell = 2,
    tags = { "legal", "consumable", "src.shop.convenience" },
    effects = { thirst = -10, fatigue = -6 },
    hooks = { stimulant = { kind="caffeine", durationSec=600, crash=true } },
  },

  sandwich = {
    label = "Sandwich",
    icon = "sandwich",
    domain = "consumable",
    stackable = true,
    maxStack = 10,
    buy = 12,
    sell = 3,
    tags = { "legal", "consumable", "src.shop.convenience", "src.shop.food" },
    effects = { hunger = -22 },
  },

  chocolate_brownie = {
    label = "Chocolate Brownie",
    icon = "chocolate-brownie",
    domain = "consumable",
    stackable = true,
    maxStack = 10,
    buy = 7,
    sell = 1,
    tags = { "legal", "consumable", "src.shop.convenience" },
    effects = { hunger = -10, stress = -2 },
  },
}
